### ISSUE TITLE
Feature: Remove dependency on deprecated Python2.7

### ISSUE THREAD

**Issue by cheruvian** [alexa-games/litexa#158]
# Feature Request
[It finally happened... Python2.7 is dead](https://pythonclock.org/). Let's remove the dependency that litexa has on it.

## Current Litexa Version
0.4.0

## Current Behavior
```
> lame@1.2.4 install C:\Documents and Settings\USER\workspaces\litexa\node_modules\lame
> node-gyp rebuild


C:\Documents and Settings\USER\workspaces\litexa\node_modules\lame>if not defined npm_config_node_gyp (node "C:\Users\USER\AppData\Roaming\nvm\v12.9.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\USER\AppData\Roaming\nvm\v12.9.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python
gyp ERR! find Python checking Python explicitly set from command line or npm configuration
gyp ERR! find Python - "--python=" or "npm config get python" is "C:/Users/USER/AppData/Local/Programs/Python/Python38-32/python"
gyp ERR! find Python - executable path is "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\python.exe"
gyp ERR! find Python - version is "3.8.2"
gyp ERR! find Python - version is 3.8.2 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking Python explicitly set from environment variable PYTHON
gyp ERR! find Python - process.env.PYTHON is "C:/Users/USER/AppData/Local/Programs/Python/Python38-32/python"
gyp ERR! find Python - executable path is "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\python.exe"
gyp ERR! find Python - version is "3.8.2"
gyp ERR! find Python - version is 3.8.2 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - executable path is "C:\Users\USER\AppData\Local\Programs\Python\Python38-32\python.exe"
gyp ERR! find Python - version is "3.8.2"
gyp ERR! find Python - version is 3.8.2 - should be >=2.6.0 <3.0.0
gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python 2.7.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Users\USER\AppData\Roaming\nvm\v12.9.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:303:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Users\USER\AppData\Roaming\nvm\v12.9.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:132:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\USER\AppData\Roaming\nvm\v12.9.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:221:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Users\USER\AppData\Roaming\nvm\v12.9.1\node_modules\npm\node_modules\node-gyp\lib\find-python.js:267:16)
gyp ERR! stack     at exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:314:5)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:456:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:77:11)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\Roaming\\nvm\\v12.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

```

## Additional Information
Seems like it might be `lame`?
https://github.com/TooTallNate/node-lame/issues/19

I haven't dug too far into it... doing the thing instead (installing Python2.7)

**Comment by joseifert** [comment]
Hi cheruvian. Yes, the issue you're seeing is due to the `lame` dependency of the `@litexa/assets-wav` package. As explained in the warning in https://litexa.com/book/appendix-wav-conversion.html#installation this currently makes it impossible to install that Litexa package on Node 12+.

We've reached out to the maintainers for the `lame` package, but haven't yet heard back. Since `@litexa/assets-wav` is a completely optional extension that can still be used on Node 10.x we've opted against removing it for now.

If you have any further questions, please let us know.

**Comment by cheruvian** [comment]
Ah, I see, didn't come across that page since I wasn't trying to do wav conversion. Was preparing a documentation pull request and when trying to build the project it failed with that message.

Good to know, not sure if there's a better way of surfacing/linking to the warning from the build output but if we can think of one it may be helpful to others
